#!/usr/bin/env bash

set -euo pipefail

now () {
    date +%s.%N
}

target_sanitize="$WD/bin/main_sanitize"
target_valgrind="$WD/bin/main_valgrind"
flags=(
    "-fdelete-null-pointer-checks"
    "-fshort-enums"
    "-fsingle-precision-constant"
    "-march=native"
    "-O3"
    "-std=gnu11"
    "-Wall"
    "-Wbad-function-cast"
    "-Wcast-align"
    "-Wcast-align=strict"
    "-Wcast-qual"
    "-Wconversion"
    "-Wdate-time"
    "-Wdouble-promotion"
    "-Wduplicated-branches"
    "-Wduplicated-cond"
    "-Werror"
    "-Wextra"
    "-Wfatal-errors"
    "-Wfloat-equal"
    "-Wformat=2"
    "-Wformat-signedness"
    "-Winline"
    "-Wlogical-op"
    "-Wmissing-declarations"
    "-Wmissing-include-dirs"
    "-Wmissing-prototypes"
    "-Wnested-externs"
    "-Wnull-dereference"
    "-Wpacked"
    "-Wpedantic"
    "-Wpointer-arith"
    "-Wredundant-decls"
    "-Wshadow"
    "-Wstack-protector"
    "-Wstrict-prototypes"
    "-Wswitch-enum"
    "-Wtrampolines"
    "-Wundef"
    "-Wunused"
    "-Wunused-macros"
    "-Wwrite-strings"
)
flags_sanitize=(
    "-fsanitize=address"
    "-fsanitize-address-use-after-scope"
    "-fsanitize=alignment"
    "-fsanitize=bool"
    "-fsanitize=bounds"
    "-fsanitize=bounds-strict"
    "-fsanitize=builtin"
    "-fsanitize=enum"
    "-fsanitize=float-cast-overflow"
    "-fsanitize=float-divide-by-zero"
    "-fsanitize=integer-divide-by-zero"
    "-fsanitize=leak"
    "-fsanitize=nonnull-attribute"
    "-fsanitize=null"
    "-fsanitize=object-size"
    "-fsanitize=pointer-overflow"
    "-fsanitize=returns-nonnull-attribute"
    "-fsanitize=shift"
    "-fsanitize=shift-base"
    "-fsanitize=shift-exponent"
    "-fsanitize=signed-integer-overflow"
    "-fsanitize=undefined"
    "-fsanitize-undefined-trap-on-error"
    "-fsanitize=unreachable"
    "-fsanitize=vla-bound"
)
files=(
    main.c
)

clang-format -i -verbose "$WD/src"/* 2>&1 | sed 's/\/.*\///g'
cppcheck --enable=all --suppress=missingIncludeSystem "$WD/src" \
    | sed 's/\/.*\/\(.*\) \.\.\./\1/g'
(
    start=$(now)
    cp "$WD/src"/* "$WD/build"
    cd "$WD/build"
    gcc -g -o "$target_valgrind" "${flags[@]}" -lm -pthread "${files[@]}"
    gcc \
        -o "$target_sanitize" \
        "${flags[@]}" \
        "${flags_sanitize[@]}" \
        -lm \
        -pthread \
        "${files[@]}"
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\n\".format(${end} - ${start}))"
)
"$target_sanitize" "$WD/out/main.bmp"
